/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAddRouteImport } from './routes/app.add'
import { Route as AppArchivesRouteImport } from './routes/app.archives'
import { Route as AppArrivalHallRouteImport } from './routes/app.arrival-hall'
import { Route as AppCommonsRouteImport } from './routes/app.commons'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppEmailRouteImport } from './routes/app.email'
import { Route as AppFilesISharedRouteImport } from './routes/app.files-i-shared'
import { Route as AppGalleryRouteImport } from './routes/app.gallery'
import { Route as AppIncomingRouteImport } from './routes/app.incoming'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppMoviesRouteImport } from './routes/app.movies'
import { Route as AppMusicRouteImport } from './routes/app.music'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppPersonalVideosRouteImport } from './routes/app.personal-videos'
import { Route as AppReadingRoomRouteImport } from './routes/app.reading-room'
import { Route as AppRoutingMemoryRouteImport } from './routes/app.routing-memory'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as AppVaultControlRouteImport } from './routes/app.vault-control'
import { Route as EnrolTokenRouteImport } from './routes/enrol.$token'
import { Route as RecoverTokenRouteImport } from './routes/recover.$token'
import { Route as AppGalleryIndexRouteImport } from './routes/app.gallery.index'
import { Route as AppGalleryPhotoIdRouteImport } from './routes/app.gallery.$photoId'
import { Route as AppMoviesIndexRouteImport } from './routes/app.movies.index'
import { Route as AppMoviesMovieIdRouteImport } from './routes/app.movies.$movieId'
import { Route as AppMoviesTvShowsRouteImport } from './routes/app.movies.tv-shows'
import { Route as AppPeopleIndexRouteImport } from './routes/app.people.index'
import { Route as AppPeoplePersonIdRouteImport } from './routes/app.people.$personId'
import { Route as AppVaultControlIndexRouteImport } from './routes/app.vault-control.index'
import { Route as AppVaultControlFederationRouteImport } from './routes/app.vault-control.federation'
import { Route as AppVaultControlIntakeRouteImport } from './routes/app.vault-control.intake'
import { Route as AppVaultControlOverviewRouteImport } from './routes/app.vault-control.overview'
import { Route as AppVaultControlRecoveryRouteImport } from './routes/app.vault-control.recovery'
import { Route as AppVaultControlServicesRouteImport } from './routes/app.vault-control.services'
import { Route as AppVaultControlStorageRouteImport } from './routes/app.vault-control.storage'
import { Route as AppVaultControlUsersRouteImport } from './routes/app.vault-control.users'
import { Route as AppMoviesTvShowsIndexRouteImport } from './routes/app.movies.tv-shows.index'
import { Route as AppMoviesTvShowsShowIdRouteImport } from './routes/app.movies.tv-shows.$showId'
import { Route as AppReadingRoomPublicationIdReadRouteImport } from './routes/app.reading-room.$publicationId.read'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppArchivesRoute = AppArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => AppRoute,
} as any)
const AppArrivalHallRoute = AppArrivalHallRouteImport.update({
  id: '/arrival-hall',
  path: '/arrival-hall',
  getParentRoute: () => AppRoute,
} as any)
const AppCommonsRoute = AppCommonsRouteImport.update({
  id: '/commons',
  path: '/commons',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesISharedRoute = AppFilesISharedRouteImport.update({
  id: '/files-i-shared',
  path: '/files-i-shared',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomingRoute = AppIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesRoute = AppMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicRoute = AppMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalVideosRoute = AppPersonalVideosRouteImport.update({
  id: '/personal-videos',
  path: '/personal-videos',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingRoomRoute = AppReadingRoomRouteImport.update({
  id: '/reading-room',
  path: '/reading-room',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingMemoryRoute = AppRoutingMemoryRouteImport.update({
  id: '/routing-memory',
  path: '/routing-memory',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultControlRoute = AppVaultControlRouteImport.update({
  id: '/vault-control',
  path: '/vault-control',
  getParentRoute: () => AppRoute,
} as any)
const EnrolTokenRoute = EnrolTokenRouteImport.update({
  id: '/enrol/$token',
  path: '/enrol/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverTokenRoute = RecoverTokenRouteImport.update({
  id: '/recover/$token',
  path: '/recover/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGalleryIndexRoute = AppGalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGalleryRoute,
} as any)
const AppGalleryPhotoIdRoute = AppGalleryPhotoIdRouteImport.update({
  id: '/$photoId',
  path: '/$photoId',
  getParentRoute: () => AppGalleryRoute,
} as any)
const AppMoviesIndexRoute = AppMoviesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoviesRoute,
} as any)
const AppMoviesMovieIdRoute = AppMoviesMovieIdRouteImport.update({
  id: '/$movieId',
  path: '/$movieId',
  getParentRoute: () => AppMoviesRoute,
} as any)
const AppMoviesTvShowsRoute = AppMoviesTvShowsRouteImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => AppMoviesRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppVaultControlIndexRoute = AppVaultControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVaultControlRoute,
} as any)
const AppVaultControlFederationRoute =
  AppVaultControlFederationRouteImport.update({
    id: '/federation',
    path: '/federation',
    getParentRoute: () => AppVaultControlRoute,
  } as any)
const AppVaultControlIntakeRoute = AppVaultControlIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppVaultControlRoute,
} as any)
const AppVaultControlOverviewRoute = AppVaultControlOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppVaultControlRoute,
} as any)
const AppVaultControlRecoveryRoute = AppVaultControlRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AppVaultControlRoute,
} as any)
const AppVaultControlServicesRoute = AppVaultControlServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppVaultControlRoute,
} as any)
const AppVaultControlStorageRoute = AppVaultControlStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppVaultControlRoute,
} as any)
const AppVaultControlUsersRoute = AppVaultControlUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppVaultControlRoute,
} as any)
const AppMoviesTvShowsIndexRoute = AppMoviesTvShowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoviesTvShowsRoute,
} as any)
const AppMoviesTvShowsShowIdRoute = AppMoviesTvShowsShowIdRouteImport.update({
  id: '/$showId',
  path: '/$showId',
  getParentRoute: () => AppMoviesTvShowsRoute,
} as any)
const AppReadingRoomPublicationIdReadRoute =
  AppReadingRoomPublicationIdReadRouteImport.update({
    id: '/$publicationId/read',
    path: '/$publicationId/read',
    getParentRoute: () => AppReadingRoomRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/app/add': typeof AppAddRoute
  '/app/archives': typeof AppArchivesRoute
  '/app/arrival-hall': typeof AppArrivalHallRoute
  '/app/commons': typeof AppCommonsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/files-i-shared': typeof AppFilesISharedRoute
  '/app/gallery': typeof AppGalleryRouteWithChildren
  '/app/incoming': typeof AppIncomingRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/movies': typeof AppMoviesRouteWithChildren
  '/app/music': typeof AppMusicRoute
  '/app/people': typeof AppPeopleRouteWithChildren
  '/app/personal-videos': typeof AppPersonalVideosRoute
  '/app/reading-room': typeof AppReadingRoomRouteWithChildren
  '/app/routing-memory': typeof AppRoutingMemoryRoute
  '/app/security': typeof AppSecurityRoute
  '/app/vault-control': typeof AppVaultControlRouteWithChildren
  '/enrol/$token': typeof EnrolTokenRoute
  '/recover/$token': typeof RecoverTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/gallery/$photoId': typeof AppGalleryPhotoIdRoute
  '/app/movies/$movieId': typeof AppMoviesMovieIdRoute
  '/app/movies/tv-shows': typeof AppMoviesTvShowsRouteWithChildren
  '/app/people/$personId': typeof AppPeoplePersonIdRoute
  '/app/vault-control/federation': typeof AppVaultControlFederationRoute
  '/app/vault-control/intake': typeof AppVaultControlIntakeRoute
  '/app/vault-control/overview': typeof AppVaultControlOverviewRoute
  '/app/vault-control/recovery': typeof AppVaultControlRecoveryRoute
  '/app/vault-control/services': typeof AppVaultControlServicesRoute
  '/app/vault-control/storage': typeof AppVaultControlStorageRoute
  '/app/vault-control/users': typeof AppVaultControlUsersRoute
  '/app/gallery/': typeof AppGalleryIndexRoute
  '/app/movies/': typeof AppMoviesIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/vault-control/': typeof AppVaultControlIndexRoute
  '/app/movies/tv-shows/$showId': typeof AppMoviesTvShowsShowIdRoute
  '/app/reading-room/$publicationId/read': typeof AppReadingRoomPublicationIdReadRoute
  '/app/movies/tv-shows/': typeof AppMoviesTvShowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/app/add': typeof AppAddRoute
  '/app/archives': typeof AppArchivesRoute
  '/app/arrival-hall': typeof AppArrivalHallRoute
  '/app/commons': typeof AppCommonsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/files-i-shared': typeof AppFilesISharedRoute
  '/app/incoming': typeof AppIncomingRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/music': typeof AppMusicRoute
  '/app/personal-videos': typeof AppPersonalVideosRoute
  '/app/reading-room': typeof AppReadingRoomRouteWithChildren
  '/app/routing-memory': typeof AppRoutingMemoryRoute
  '/app/security': typeof AppSecurityRoute
  '/enrol/$token': typeof EnrolTokenRoute
  '/recover/$token': typeof RecoverTokenRoute
  '/app': typeof AppIndexRoute
  '/app/gallery/$photoId': typeof AppGalleryPhotoIdRoute
  '/app/movies/$movieId': typeof AppMoviesMovieIdRoute
  '/app/people/$personId': typeof AppPeoplePersonIdRoute
  '/app/vault-control/federation': typeof AppVaultControlFederationRoute
  '/app/vault-control/intake': typeof AppVaultControlIntakeRoute
  '/app/vault-control/overview': typeof AppVaultControlOverviewRoute
  '/app/vault-control/recovery': typeof AppVaultControlRecoveryRoute
  '/app/vault-control/services': typeof AppVaultControlServicesRoute
  '/app/vault-control/storage': typeof AppVaultControlStorageRoute
  '/app/vault-control/users': typeof AppVaultControlUsersRoute
  '/app/gallery': typeof AppGalleryIndexRoute
  '/app/movies': typeof AppMoviesIndexRoute
  '/app/people': typeof AppPeopleIndexRoute
  '/app/vault-control': typeof AppVaultControlIndexRoute
  '/app/movies/tv-shows/$showId': typeof AppMoviesTvShowsShowIdRoute
  '/app/reading-room/$publicationId/read': typeof AppReadingRoomPublicationIdReadRoute
  '/app/movies/tv-shows': typeof AppMoviesTvShowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/app/add': typeof AppAddRoute
  '/app/archives': typeof AppArchivesRoute
  '/app/arrival-hall': typeof AppArrivalHallRoute
  '/app/commons': typeof AppCommonsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/files-i-shared': typeof AppFilesISharedRoute
  '/app/gallery': typeof AppGalleryRouteWithChildren
  '/app/incoming': typeof AppIncomingRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/movies': typeof AppMoviesRouteWithChildren
  '/app/music': typeof AppMusicRoute
  '/app/people': typeof AppPeopleRouteWithChildren
  '/app/personal-videos': typeof AppPersonalVideosRoute
  '/app/reading-room': typeof AppReadingRoomRouteWithChildren
  '/app/routing-memory': typeof AppRoutingMemoryRoute
  '/app/security': typeof AppSecurityRoute
  '/app/vault-control': typeof AppVaultControlRouteWithChildren
  '/enrol/$token': typeof EnrolTokenRoute
  '/recover/$token': typeof RecoverTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/gallery/$photoId': typeof AppGalleryPhotoIdRoute
  '/app/movies/$movieId': typeof AppMoviesMovieIdRoute
  '/app/movies/tv-shows': typeof AppMoviesTvShowsRouteWithChildren
  '/app/people/$personId': typeof AppPeoplePersonIdRoute
  '/app/vault-control/federation': typeof AppVaultControlFederationRoute
  '/app/vault-control/intake': typeof AppVaultControlIntakeRoute
  '/app/vault-control/overview': typeof AppVaultControlOverviewRoute
  '/app/vault-control/recovery': typeof AppVaultControlRecoveryRoute
  '/app/vault-control/services': typeof AppVaultControlServicesRoute
  '/app/vault-control/storage': typeof AppVaultControlStorageRoute
  '/app/vault-control/users': typeof AppVaultControlUsersRoute
  '/app/gallery/': typeof AppGalleryIndexRoute
  '/app/movies/': typeof AppMoviesIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/vault-control/': typeof AppVaultControlIndexRoute
  '/app/movies/tv-shows/$showId': typeof AppMoviesTvShowsShowIdRoute
  '/app/reading-room/$publicationId/read': typeof AppReadingRoomPublicationIdReadRoute
  '/app/movies/tv-shows/': typeof AppMoviesTvShowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/change-password'
    | '/login'
    | '/app/add'
    | '/app/archives'
    | '/app/arrival-hall'
    | '/app/commons'
    | '/app/documents'
    | '/app/email'
    | '/app/files-i-shared'
    | '/app/gallery'
    | '/app/incoming'
    | '/app/ledger'
    | '/app/movies'
    | '/app/music'
    | '/app/people'
    | '/app/personal-videos'
    | '/app/reading-room'
    | '/app/routing-memory'
    | '/app/security'
    | '/app/vault-control'
    | '/enrol/$token'
    | '/recover/$token'
    | '/app/'
    | '/app/gallery/$photoId'
    | '/app/movies/$movieId'
    | '/app/movies/tv-shows'
    | '/app/people/$personId'
    | '/app/vault-control/federation'
    | '/app/vault-control/intake'
    | '/app/vault-control/overview'
    | '/app/vault-control/recovery'
    | '/app/vault-control/services'
    | '/app/vault-control/storage'
    | '/app/vault-control/users'
    | '/app/gallery/'
    | '/app/movies/'
    | '/app/people/'
    | '/app/vault-control/'
    | '/app/movies/tv-shows/$showId'
    | '/app/reading-room/$publicationId/read'
    | '/app/movies/tv-shows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/app/add'
    | '/app/archives'
    | '/app/arrival-hall'
    | '/app/commons'
    | '/app/documents'
    | '/app/email'
    | '/app/files-i-shared'
    | '/app/incoming'
    | '/app/ledger'
    | '/app/music'
    | '/app/personal-videos'
    | '/app/reading-room'
    | '/app/routing-memory'
    | '/app/security'
    | '/enrol/$token'
    | '/recover/$token'
    | '/app'
    | '/app/gallery/$photoId'
    | '/app/movies/$movieId'
    | '/app/people/$personId'
    | '/app/vault-control/federation'
    | '/app/vault-control/intake'
    | '/app/vault-control/overview'
    | '/app/vault-control/recovery'
    | '/app/vault-control/services'
    | '/app/vault-control/storage'
    | '/app/vault-control/users'
    | '/app/gallery'
    | '/app/movies'
    | '/app/people'
    | '/app/vault-control'
    | '/app/movies/tv-shows/$showId'
    | '/app/reading-room/$publicationId/read'
    | '/app/movies/tv-shows'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/change-password'
    | '/login'
    | '/app/add'
    | '/app/archives'
    | '/app/arrival-hall'
    | '/app/commons'
    | '/app/documents'
    | '/app/email'
    | '/app/files-i-shared'
    | '/app/gallery'
    | '/app/incoming'
    | '/app/ledger'
    | '/app/movies'
    | '/app/music'
    | '/app/people'
    | '/app/personal-videos'
    | '/app/reading-room'
    | '/app/routing-memory'
    | '/app/security'
    | '/app/vault-control'
    | '/enrol/$token'
    | '/recover/$token'
    | '/app/'
    | '/app/gallery/$photoId'
    | '/app/movies/$movieId'
    | '/app/movies/tv-shows'
    | '/app/people/$personId'
    | '/app/vault-control/federation'
    | '/app/vault-control/intake'
    | '/app/vault-control/overview'
    | '/app/vault-control/recovery'
    | '/app/vault-control/services'
    | '/app/vault-control/storage'
    | '/app/vault-control/users'
    | '/app/gallery/'
    | '/app/movies/'
    | '/app/people/'
    | '/app/vault-control/'
    | '/app/movies/tv-shows/$showId'
    | '/app/reading-room/$publicationId/read'
    | '/app/movies/tv-shows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  EnrolTokenRoute: typeof EnrolTokenRoute
  RecoverTokenRoute: typeof RecoverTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add': {
      id: '/app/add'
      path: '/add'
      fullPath: '/app/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/archives': {
      id: '/app/archives'
      path: '/archives'
      fullPath: '/app/archives'
      preLoaderRoute: typeof AppArchivesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/arrival-hall': {
      id: '/app/arrival-hall'
      path: '/arrival-hall'
      fullPath: '/app/arrival-hall'
      preLoaderRoute: typeof AppArrivalHallRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commons': {
      id: '/app/commons'
      path: '/commons'
      fullPath: '/app/commons'
      preLoaderRoute: typeof AppCommonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email': {
      id: '/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files-i-shared': {
      id: '/app/files-i-shared'
      path: '/files-i-shared'
      fullPath: '/app/files-i-shared'
      preLoaderRoute: typeof AppFilesISharedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gallery': {
      id: '/app/gallery'
      path: '/gallery'
      fullPath: '/app/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incoming': {
      id: '/app/incoming'
      path: '/incoming'
      fullPath: '/app/incoming'
      preLoaderRoute: typeof AppIncomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movies': {
      id: '/app/movies'
      path: '/movies'
      fullPath: '/app/movies'
      preLoaderRoute: typeof AppMoviesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/music': {
      id: '/app/music'
      path: '/music'
      fullPath: '/app/music'
      preLoaderRoute: typeof AppMusicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/personal-videos': {
      id: '/app/personal-videos'
      path: '/personal-videos'
      fullPath: '/app/personal-videos'
      preLoaderRoute: typeof AppPersonalVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reading-room': {
      id: '/app/reading-room'
      path: '/reading-room'
      fullPath: '/app/reading-room'
      preLoaderRoute: typeof AppReadingRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routing-memory': {
      id: '/app/routing-memory'
      path: '/routing-memory'
      fullPath: '/app/routing-memory'
      preLoaderRoute: typeof AppRoutingMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vault-control': {
      id: '/app/vault-control'
      path: '/vault-control'
      fullPath: '/app/vault-control'
      preLoaderRoute: typeof AppVaultControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/enrol/$token': {
      id: '/enrol/$token'
      path: '/enrol/$token'
      fullPath: '/enrol/$token'
      preLoaderRoute: typeof EnrolTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/$token': {
      id: '/recover/$token'
      path: '/recover/$token'
      fullPath: '/recover/$token'
      preLoaderRoute: typeof RecoverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gallery/': {
      id: '/app/gallery/'
      path: '/'
      fullPath: '/app/gallery/'
      preLoaderRoute: typeof AppGalleryIndexRouteImport
      parentRoute: typeof AppGalleryRoute
    }
    '/app/gallery/$photoId': {
      id: '/app/gallery/$photoId'
      path: '/$photoId'
      fullPath: '/app/gallery/$photoId'
      preLoaderRoute: typeof AppGalleryPhotoIdRouteImport
      parentRoute: typeof AppGalleryRoute
    }
    '/app/movies/': {
      id: '/app/movies/'
      path: '/'
      fullPath: '/app/movies/'
      preLoaderRoute: typeof AppMoviesIndexRouteImport
      parentRoute: typeof AppMoviesRoute
    }
    '/app/movies/$movieId': {
      id: '/app/movies/$movieId'
      path: '/$movieId'
      fullPath: '/app/movies/$movieId'
      preLoaderRoute: typeof AppMoviesMovieIdRouteImport
      parentRoute: typeof AppMoviesRoute
    }
    '/app/movies/tv-shows': {
      id: '/app/movies/tv-shows'
      path: '/tv-shows'
      fullPath: '/app/movies/tv-shows'
      preLoaderRoute: typeof AppMoviesTvShowsRouteImport
      parentRoute: typeof AppMoviesRoute
    }
    '/app/people/': {
      id: '/app/people/'
      path: '/'
      fullPath: '/app/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/app/people/$personId': {
      id: '/app/people/$personId'
      path: '/$personId'
      fullPath: '/app/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/app/vault-control/': {
      id: '/app/vault-control/'
      path: '/'
      fullPath: '/app/vault-control/'
      preLoaderRoute: typeof AppVaultControlIndexRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/vault-control/federation': {
      id: '/app/vault-control/federation'
      path: '/federation'
      fullPath: '/app/vault-control/federation'
      preLoaderRoute: typeof AppVaultControlFederationRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/vault-control/intake': {
      id: '/app/vault-control/intake'
      path: '/intake'
      fullPath: '/app/vault-control/intake'
      preLoaderRoute: typeof AppVaultControlIntakeRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/vault-control/overview': {
      id: '/app/vault-control/overview'
      path: '/overview'
      fullPath: '/app/vault-control/overview'
      preLoaderRoute: typeof AppVaultControlOverviewRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/vault-control/recovery': {
      id: '/app/vault-control/recovery'
      path: '/recovery'
      fullPath: '/app/vault-control/recovery'
      preLoaderRoute: typeof AppVaultControlRecoveryRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/vault-control/services': {
      id: '/app/vault-control/services'
      path: '/services'
      fullPath: '/app/vault-control/services'
      preLoaderRoute: typeof AppVaultControlServicesRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/vault-control/storage': {
      id: '/app/vault-control/storage'
      path: '/storage'
      fullPath: '/app/vault-control/storage'
      preLoaderRoute: typeof AppVaultControlStorageRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/vault-control/users': {
      id: '/app/vault-control/users'
      path: '/users'
      fullPath: '/app/vault-control/users'
      preLoaderRoute: typeof AppVaultControlUsersRouteImport
      parentRoute: typeof AppVaultControlRoute
    }
    '/app/movies/tv-shows/': {
      id: '/app/movies/tv-shows/'
      path: '/'
      fullPath: '/app/movies/tv-shows/'
      preLoaderRoute: typeof AppMoviesTvShowsIndexRouteImport
      parentRoute: typeof AppMoviesTvShowsRoute
    }
    '/app/movies/tv-shows/$showId': {
      id: '/app/movies/tv-shows/$showId'
      path: '/$showId'
      fullPath: '/app/movies/tv-shows/$showId'
      preLoaderRoute: typeof AppMoviesTvShowsShowIdRouteImport
      parentRoute: typeof AppMoviesTvShowsRoute
    }
    '/app/reading-room/$publicationId/read': {
      id: '/app/reading-room/$publicationId/read'
      path: '/$publicationId/read'
      fullPath: '/app/reading-room/$publicationId/read'
      preLoaderRoute: typeof AppReadingRoomPublicationIdReadRouteImport
      parentRoute: typeof AppReadingRoomRoute
    }
  }
}

interface AppGalleryRouteChildren {
  AppGalleryPhotoIdRoute: typeof AppGalleryPhotoIdRoute
  AppGalleryIndexRoute: typeof AppGalleryIndexRoute
}

const AppGalleryRouteChildren: AppGalleryRouteChildren = {
  AppGalleryPhotoIdRoute: AppGalleryPhotoIdRoute,
  AppGalleryIndexRoute: AppGalleryIndexRoute,
}

const AppGalleryRouteWithChildren = AppGalleryRoute._addFileChildren(
  AppGalleryRouteChildren,
)

interface AppMoviesTvShowsRouteChildren {
  AppMoviesTvShowsShowIdRoute: typeof AppMoviesTvShowsShowIdRoute
  AppMoviesTvShowsIndexRoute: typeof AppMoviesTvShowsIndexRoute
}

const AppMoviesTvShowsRouteChildren: AppMoviesTvShowsRouteChildren = {
  AppMoviesTvShowsShowIdRoute: AppMoviesTvShowsShowIdRoute,
  AppMoviesTvShowsIndexRoute: AppMoviesTvShowsIndexRoute,
}

const AppMoviesTvShowsRouteWithChildren =
  AppMoviesTvShowsRoute._addFileChildren(AppMoviesTvShowsRouteChildren)

interface AppMoviesRouteChildren {
  AppMoviesMovieIdRoute: typeof AppMoviesMovieIdRoute
  AppMoviesTvShowsRoute: typeof AppMoviesTvShowsRouteWithChildren
  AppMoviesIndexRoute: typeof AppMoviesIndexRoute
}

const AppMoviesRouteChildren: AppMoviesRouteChildren = {
  AppMoviesMovieIdRoute: AppMoviesMovieIdRoute,
  AppMoviesTvShowsRoute: AppMoviesTvShowsRouteWithChildren,
  AppMoviesIndexRoute: AppMoviesIndexRoute,
}

const AppMoviesRouteWithChildren = AppMoviesRoute._addFileChildren(
  AppMoviesRouteChildren,
)

interface AppPeopleRouteChildren {
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppPeopleRouteChildren: AppPeopleRouteChildren = {
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppPeopleRouteWithChildren = AppPeopleRoute._addFileChildren(
  AppPeopleRouteChildren,
)

interface AppReadingRoomRouteChildren {
  AppReadingRoomPublicationIdReadRoute: typeof AppReadingRoomPublicationIdReadRoute
}

const AppReadingRoomRouteChildren: AppReadingRoomRouteChildren = {
  AppReadingRoomPublicationIdReadRoute: AppReadingRoomPublicationIdReadRoute,
}

const AppReadingRoomRouteWithChildren = AppReadingRoomRoute._addFileChildren(
  AppReadingRoomRouteChildren,
)

interface AppVaultControlRouteChildren {
  AppVaultControlFederationRoute: typeof AppVaultControlFederationRoute
  AppVaultControlIntakeRoute: typeof AppVaultControlIntakeRoute
  AppVaultControlOverviewRoute: typeof AppVaultControlOverviewRoute
  AppVaultControlRecoveryRoute: typeof AppVaultControlRecoveryRoute
  AppVaultControlServicesRoute: typeof AppVaultControlServicesRoute
  AppVaultControlStorageRoute: typeof AppVaultControlStorageRoute
  AppVaultControlUsersRoute: typeof AppVaultControlUsersRoute
  AppVaultControlIndexRoute: typeof AppVaultControlIndexRoute
}

const AppVaultControlRouteChildren: AppVaultControlRouteChildren = {
  AppVaultControlFederationRoute: AppVaultControlFederationRoute,
  AppVaultControlIntakeRoute: AppVaultControlIntakeRoute,
  AppVaultControlOverviewRoute: AppVaultControlOverviewRoute,
  AppVaultControlRecoveryRoute: AppVaultControlRecoveryRoute,
  AppVaultControlServicesRoute: AppVaultControlServicesRoute,
  AppVaultControlStorageRoute: AppVaultControlStorageRoute,
  AppVaultControlUsersRoute: AppVaultControlUsersRoute,
  AppVaultControlIndexRoute: AppVaultControlIndexRoute,
}

const AppVaultControlRouteWithChildren = AppVaultControlRoute._addFileChildren(
  AppVaultControlRouteChildren,
)

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppArchivesRoute: typeof AppArchivesRoute
  AppArrivalHallRoute: typeof AppArrivalHallRoute
  AppCommonsRoute: typeof AppCommonsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmailRoute: typeof AppEmailRoute
  AppFilesISharedRoute: typeof AppFilesISharedRoute
  AppGalleryRoute: typeof AppGalleryRouteWithChildren
  AppIncomingRoute: typeof AppIncomingRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppMoviesRoute: typeof AppMoviesRouteWithChildren
  AppMusicRoute: typeof AppMusicRoute
  AppPeopleRoute: typeof AppPeopleRouteWithChildren
  AppPersonalVideosRoute: typeof AppPersonalVideosRoute
  AppReadingRoomRoute: typeof AppReadingRoomRouteWithChildren
  AppRoutingMemoryRoute: typeof AppRoutingMemoryRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppVaultControlRoute: typeof AppVaultControlRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppArchivesRoute: AppArchivesRoute,
  AppArrivalHallRoute: AppArrivalHallRoute,
  AppCommonsRoute: AppCommonsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmailRoute: AppEmailRoute,
  AppFilesISharedRoute: AppFilesISharedRoute,
  AppGalleryRoute: AppGalleryRouteWithChildren,
  AppIncomingRoute: AppIncomingRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppMoviesRoute: AppMoviesRouteWithChildren,
  AppMusicRoute: AppMusicRoute,
  AppPeopleRoute: AppPeopleRouteWithChildren,
  AppPersonalVideosRoute: AppPersonalVideosRoute,
  AppReadingRoomRoute: AppReadingRoomRouteWithChildren,
  AppRoutingMemoryRoute: AppRoutingMemoryRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppVaultControlRoute: AppVaultControlRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  EnrolTokenRoute: EnrolTokenRoute,
  RecoverTokenRoute: RecoverTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
